name: care_o_than
description: "A new Flutter project for ABHA Onboarding."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pointycastle: ^3.4.0  # Moved out of flutter block

  encrypt: ^5.0.0
  
  # For iOS styled widgets
  cupertino_icons: ^1.0.6
  
  # HTTP requests for API communication
  http: ^0.13.3

  # QR code scanning
  qr_code_scanner: ^0.4.0

  # State management
  provider: ^6.0.0

  # Shared preferences for local storage
  shared_preferences: ^2.0.6
  
  # Logging package for logging info and errors
  logging: ^1.0.2

dev_dependencies:
  # For unit and widget testing
  flutter_test:
    sdk: flutter

  # Flutter-specific linting rules
  flutter_lints: ^3.0.0
  

flutter:

  uses-material-design: true

  # Add assets and images here if needed in the future
  # assets:
  #   - assets/images/

  # Font and other customizations can go here
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
